require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ChargeWizardsController do

  # This should return the minimal set of attributes required to create a valid
  # ChargeWizard. As you add validations to ChargeWizard, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "linked_account" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ChargeWizardsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all charge_wizards as @charge_wizards" do
      charge_wizard = ChargeWizard.create! valid_attributes
      get :index, {}, valid_session
      assigns(:charge_wizards).should eq([charge_wizard])
    end
  end

  describe "GET show" do
    it "assigns the requested charge_wizard as @charge_wizard" do
      charge_wizard = ChargeWizard.create! valid_attributes
      get :show, {:id => charge_wizard.to_param}, valid_session
      assigns(:charge_wizard).should eq(charge_wizard)
    end
  end

  describe "GET new" do
    it "assigns a new charge_wizard as @charge_wizard" do
      get :new, {}, valid_session
      assigns(:charge_wizard).should be_a_new(ChargeWizard)
    end
  end

  describe "GET edit" do
    it "assigns the requested charge_wizard as @charge_wizard" do
      charge_wizard = ChargeWizard.create! valid_attributes
      get :edit, {:id => charge_wizard.to_param}, valid_session
      assigns(:charge_wizard).should eq(charge_wizard)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ChargeWizard" do
        expect {
          post :create, {:charge_wizard => valid_attributes}, valid_session
        }.to change(ChargeWizard, :count).by(1)
      end

      it "assigns a newly created charge_wizard as @charge_wizard" do
        post :create, {:charge_wizard => valid_attributes}, valid_session
        assigns(:charge_wizard).should be_a(ChargeWizard)
        assigns(:charge_wizard).should be_persisted
      end

      it "redirects to the created charge_wizard" do
        post :create, {:charge_wizard => valid_attributes}, valid_session
        response.should redirect_to(ChargeWizard.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved charge_wizard as @charge_wizard" do
        # Trigger the behavior that occurs when invalid params are submitted
        ChargeWizard.any_instance.stub(:save).and_return(false)
        post :create, {:charge_wizard => { "linked_account" => "invalid value" }}, valid_session
        assigns(:charge_wizard).should be_a_new(ChargeWizard)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ChargeWizard.any_instance.stub(:save).and_return(false)
        post :create, {:charge_wizard => { "linked_account" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested charge_wizard" do
        charge_wizard = ChargeWizard.create! valid_attributes
        # Assuming there are no other charge_wizards in the database, this
        # specifies that the ChargeWizard created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ChargeWizard.any_instance.should_receive(:update).with({ "linked_account" => "" })
        put :update, {:id => charge_wizard.to_param, :charge_wizard => { "linked_account" => "" }}, valid_session
      end

      it "assigns the requested charge_wizard as @charge_wizard" do
        charge_wizard = ChargeWizard.create! valid_attributes
        put :update, {:id => charge_wizard.to_param, :charge_wizard => valid_attributes}, valid_session
        assigns(:charge_wizard).should eq(charge_wizard)
      end

      it "redirects to the charge_wizard" do
        charge_wizard = ChargeWizard.create! valid_attributes
        put :update, {:id => charge_wizard.to_param, :charge_wizard => valid_attributes}, valid_session
        response.should redirect_to(charge_wizard)
      end
    end

    describe "with invalid params" do
      it "assigns the charge_wizard as @charge_wizard" do
        charge_wizard = ChargeWizard.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ChargeWizard.any_instance.stub(:save).and_return(false)
        put :update, {:id => charge_wizard.to_param, :charge_wizard => { "linked_account" => "invalid value" }}, valid_session
        assigns(:charge_wizard).should eq(charge_wizard)
      end

      it "re-renders the 'edit' template" do
        charge_wizard = ChargeWizard.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ChargeWizard.any_instance.stub(:save).and_return(false)
        put :update, {:id => charge_wizard.to_param, :charge_wizard => { "linked_account" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested charge_wizard" do
      charge_wizard = ChargeWizard.create! valid_attributes
      expect {
        delete :destroy, {:id => charge_wizard.to_param}, valid_session
      }.to change(ChargeWizard, :count).by(-1)
    end

    it "redirects to the charge_wizards list" do
      charge_wizard = ChargeWizard.create! valid_attributes
      delete :destroy, {:id => charge_wizard.to_param}, valid_session
      response.should redirect_to(charge_wizards_url)
    end
  end

end
