require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe InviteRequestsController do

  # This should return the minimal set of attributes required to create a valid
  # InviteRequest. As you add validations to InviteRequest, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "email" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # InviteRequestsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all invite_requests as @invite_requests" do
      invite_request = InviteRequest.create! valid_attributes
      get :index, {}, valid_session
      assigns(:invite_requests).should eq([invite_request])
    end
  end

  describe "GET show" do
    it "assigns the requested invite_request as @invite_request" do
      invite_request = InviteRequest.create! valid_attributes
      get :show, {:id => invite_request.to_param}, valid_session
      assigns(:invite_request).should eq(invite_request)
    end
  end

  describe "GET new" do
    it "assigns a new invite_request as @invite_request" do
      get :new, {}, valid_session
      assigns(:invite_request).should be_a_new(InviteRequest)
    end
  end

  describe "GET edit" do
    it "assigns the requested invite_request as @invite_request" do
      invite_request = InviteRequest.create! valid_attributes
      get :edit, {:id => invite_request.to_param}, valid_session
      assigns(:invite_request).should eq(invite_request)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new InviteRequest" do
        expect {
          post :create, {:invite_request => valid_attributes}, valid_session
        }.to change(InviteRequest, :count).by(1)
      end

      it "assigns a newly created invite_request as @invite_request" do
        post :create, {:invite_request => valid_attributes}, valid_session
        assigns(:invite_request).should be_a(InviteRequest)
        assigns(:invite_request).should be_persisted
      end

      it "redirects to the created invite_request" do
        post :create, {:invite_request => valid_attributes}, valid_session
        response.should redirect_to(InviteRequest.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved invite_request as @invite_request" do
        # Trigger the behavior that occurs when invalid params are submitted
        InviteRequest.any_instance.stub(:save).and_return(false)
        post :create, {:invite_request => { "email" => "invalid value" }}, valid_session
        assigns(:invite_request).should be_a_new(InviteRequest)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        InviteRequest.any_instance.stub(:save).and_return(false)
        post :create, {:invite_request => { "email" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested invite_request" do
        invite_request = InviteRequest.create! valid_attributes
        # Assuming there are no other invite_requests in the database, this
        # specifies that the InviteRequest created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        InviteRequest.any_instance.should_receive(:update).with({ "email" => "MyString" })
        put :update, {:id => invite_request.to_param, :invite_request => { "email" => "MyString" }}, valid_session
      end

      it "assigns the requested invite_request as @invite_request" do
        invite_request = InviteRequest.create! valid_attributes
        put :update, {:id => invite_request.to_param, :invite_request => valid_attributes}, valid_session
        assigns(:invite_request).should eq(invite_request)
      end

      it "redirects to the invite_request" do
        invite_request = InviteRequest.create! valid_attributes
        put :update, {:id => invite_request.to_param, :invite_request => valid_attributes}, valid_session
        response.should redirect_to(invite_request)
      end
    end

    describe "with invalid params" do
      it "assigns the invite_request as @invite_request" do
        invite_request = InviteRequest.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        InviteRequest.any_instance.stub(:save).and_return(false)
        put :update, {:id => invite_request.to_param, :invite_request => { "email" => "invalid value" }}, valid_session
        assigns(:invite_request).should eq(invite_request)
      end

      it "re-renders the 'edit' template" do
        invite_request = InviteRequest.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        InviteRequest.any_instance.stub(:save).and_return(false)
        put :update, {:id => invite_request.to_param, :invite_request => { "email" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested invite_request" do
      invite_request = InviteRequest.create! valid_attributes
      expect {
        delete :destroy, {:id => invite_request.to_param}, valid_session
      }.to change(InviteRequest, :count).by(-1)
    end

    it "redirects to the invite_requests list" do
      invite_request = InviteRequest.create! valid_attributes
      delete :destroy, {:id => invite_request.to_param}, valid_session
      response.should redirect_to(invite_requests_url)
    end
  end

end
