require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MerchantAliasesController do

  # This should return the minimal set of attributes required to create a valid
  # MerchantAlias. As you add validations to MerchantAlias, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "alias" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MerchantAliasesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all merchant_aliases as @merchant_aliases" do
      merchant_alias = MerchantAlias.create! valid_attributes
      get :index, {}, valid_session
      assigns(:merchant_aliases).should eq([merchant_alias])
    end
  end

  describe "GET show" do
    it "assigns the requested merchant_alias as @merchant_alias" do
      merchant_alias = MerchantAlias.create! valid_attributes
      get :show, {:id => merchant_alias.to_param}, valid_session
      assigns(:merchant_alias).should eq(merchant_alias)
    end
  end

  describe "GET new" do
    it "assigns a new merchant_alias as @merchant_alias" do
      get :new, {}, valid_session
      assigns(:merchant_alias).should be_a_new(MerchantAlias)
    end
  end

  describe "GET edit" do
    it "assigns the requested merchant_alias as @merchant_alias" do
      merchant_alias = MerchantAlias.create! valid_attributes
      get :edit, {:id => merchant_alias.to_param}, valid_session
      assigns(:merchant_alias).should eq(merchant_alias)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new MerchantAlias" do
        expect {
          post :create, {:merchant_alias => valid_attributes}, valid_session
        }.to change(MerchantAlias, :count).by(1)
      end

      it "assigns a newly created merchant_alias as @merchant_alias" do
        post :create, {:merchant_alias => valid_attributes}, valid_session
        assigns(:merchant_alias).should be_a(MerchantAlias)
        assigns(:merchant_alias).should be_persisted
      end

      it "redirects to the created merchant_alias" do
        post :create, {:merchant_alias => valid_attributes}, valid_session
        response.should redirect_to(MerchantAlias.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved merchant_alias as @merchant_alias" do
        # Trigger the behavior that occurs when invalid params are submitted
        MerchantAlias.any_instance.stub(:save).and_return(false)
        post :create, {:merchant_alias => { "alias" => "invalid value" }}, valid_session
        assigns(:merchant_alias).should be_a_new(MerchantAlias)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        MerchantAlias.any_instance.stub(:save).and_return(false)
        post :create, {:merchant_alias => { "alias" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested merchant_alias" do
        merchant_alias = MerchantAlias.create! valid_attributes
        # Assuming there are no other merchant_aliases in the database, this
        # specifies that the MerchantAlias created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        MerchantAlias.any_instance.should_receive(:update).with({ "alias" => "MyString" })
        put :update, {:id => merchant_alias.to_param, :merchant_alias => { "alias" => "MyString" }}, valid_session
      end

      it "assigns the requested merchant_alias as @merchant_alias" do
        merchant_alias = MerchantAlias.create! valid_attributes
        put :update, {:id => merchant_alias.to_param, :merchant_alias => valid_attributes}, valid_session
        assigns(:merchant_alias).should eq(merchant_alias)
      end

      it "redirects to the merchant_alias" do
        merchant_alias = MerchantAlias.create! valid_attributes
        put :update, {:id => merchant_alias.to_param, :merchant_alias => valid_attributes}, valid_session
        response.should redirect_to(merchant_alias)
      end
    end

    describe "with invalid params" do
      it "assigns the merchant_alias as @merchant_alias" do
        merchant_alias = MerchantAlias.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MerchantAlias.any_instance.stub(:save).and_return(false)
        put :update, {:id => merchant_alias.to_param, :merchant_alias => { "alias" => "invalid value" }}, valid_session
        assigns(:merchant_alias).should eq(merchant_alias)
      end

      it "re-renders the 'edit' template" do
        merchant_alias = MerchantAlias.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MerchantAlias.any_instance.stub(:save).and_return(false)
        put :update, {:id => merchant_alias.to_param, :merchant_alias => { "alias" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested merchant_alias" do
      merchant_alias = MerchantAlias.create! valid_attributes
      expect {
        delete :destroy, {:id => merchant_alias.to_param}, valid_session
      }.to change(MerchantAlias, :count).by(-1)
    end

    it "redirects to the merchant_aliases list" do
      merchant_alias = MerchantAlias.create! valid_attributes
      delete :destroy, {:id => merchant_alias.to_param}, valid_session
      response.should redirect_to(merchant_aliases_url)
    end
  end

end
