require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TransactionDataRequestsController do

  # This should return the minimal set of attributes required to create a valid
  # TransactionDataRequest. As you add validations to TransactionDataRequest, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "user" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TransactionDataRequestsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all transaction_data_requests as @transaction_data_requests" do
      transaction_data_request = TransactionDataRequest.create! valid_attributes
      get :index, {}, valid_session
      assigns(:transaction_data_requests).should eq([transaction_data_request])
    end
  end

  describe "GET show" do
    it "assigns the requested transaction_data_request as @transaction_data_request" do
      transaction_data_request = TransactionDataRequest.create! valid_attributes
      get :show, {:id => transaction_data_request.to_param}, valid_session
      assigns(:transaction_data_request).should eq(transaction_data_request)
    end
  end

  describe "GET new" do
    it "assigns a new transaction_data_request as @transaction_data_request" do
      get :new, {}, valid_session
      assigns(:transaction_data_request).should be_a_new(TransactionDataRequest)
    end
  end

  describe "GET edit" do
    it "assigns the requested transaction_data_request as @transaction_data_request" do
      transaction_data_request = TransactionDataRequest.create! valid_attributes
      get :edit, {:id => transaction_data_request.to_param}, valid_session
      assigns(:transaction_data_request).should eq(transaction_data_request)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TransactionDataRequest" do
        expect {
          post :create, {:transaction_data_request => valid_attributes}, valid_session
        }.to change(TransactionDataRequest, :count).by(1)
      end

      it "assigns a newly created transaction_data_request as @transaction_data_request" do
        post :create, {:transaction_data_request => valid_attributes}, valid_session
        assigns(:transaction_data_request).should be_a(TransactionDataRequest)
        assigns(:transaction_data_request).should be_persisted
      end

      it "redirects to the created transaction_data_request" do
        post :create, {:transaction_data_request => valid_attributes}, valid_session
        response.should redirect_to(TransactionDataRequest.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved transaction_data_request as @transaction_data_request" do
        # Trigger the behavior that occurs when invalid params are submitted
        TransactionDataRequest.any_instance.stub(:save).and_return(false)
        post :create, {:transaction_data_request => { "user" => "invalid value" }}, valid_session
        assigns(:transaction_data_request).should be_a_new(TransactionDataRequest)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TransactionDataRequest.any_instance.stub(:save).and_return(false)
        post :create, {:transaction_data_request => { "user" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested transaction_data_request" do
        transaction_data_request = TransactionDataRequest.create! valid_attributes
        # Assuming there are no other transaction_data_requests in the database, this
        # specifies that the TransactionDataRequest created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TransactionDataRequest.any_instance.should_receive(:update).with({ "user" => "" })
        put :update, {:id => transaction_data_request.to_param, :transaction_data_request => { "user" => "" }}, valid_session
      end

      it "assigns the requested transaction_data_request as @transaction_data_request" do
        transaction_data_request = TransactionDataRequest.create! valid_attributes
        put :update, {:id => transaction_data_request.to_param, :transaction_data_request => valid_attributes}, valid_session
        assigns(:transaction_data_request).should eq(transaction_data_request)
      end

      it "redirects to the transaction_data_request" do
        transaction_data_request = TransactionDataRequest.create! valid_attributes
        put :update, {:id => transaction_data_request.to_param, :transaction_data_request => valid_attributes}, valid_session
        response.should redirect_to(transaction_data_request)
      end
    end

    describe "with invalid params" do
      it "assigns the transaction_data_request as @transaction_data_request" do
        transaction_data_request = TransactionDataRequest.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TransactionDataRequest.any_instance.stub(:save).and_return(false)
        put :update, {:id => transaction_data_request.to_param, :transaction_data_request => { "user" => "invalid value" }}, valid_session
        assigns(:transaction_data_request).should eq(transaction_data_request)
      end

      it "re-renders the 'edit' template" do
        transaction_data_request = TransactionDataRequest.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TransactionDataRequest.any_instance.stub(:save).and_return(false)
        put :update, {:id => transaction_data_request.to_param, :transaction_data_request => { "user" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested transaction_data_request" do
      transaction_data_request = TransactionDataRequest.create! valid_attributes
      expect {
        delete :destroy, {:id => transaction_data_request.to_param}, valid_session
      }.to change(TransactionDataRequest, :count).by(-1)
    end

    it "redirects to the transaction_data_requests list" do
      transaction_data_request = TransactionDataRequest.create! valid_attributes
      delete :destroy, {:id => transaction_data_request.to_param}, valid_session
      response.should redirect_to(transaction_data_requests_url)
    end
  end

end
